<a href="https://colab.research.google.com/github/Nayeemhabib/Machine_Learning_Projects/blob/main/Machine_Learning_Projects/Spam_mail_Filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** A DETALED DTUDY ON EMAIL SPAM FILTERING TECHNIQUES**
* We present a comprehensive review of the most effective content-based e-mail spam filtering techniques. We focus primarily on Machine Learning-based spam filters and their variants and report on a broad review ranging from surveying the relevant ideas, efforts, effectiveness, and current progress. The initial exposition of the background examines the basics of e-mail spam filtering, the evolving nature of spam, spammers playing cat-and-mouse with e-mail service providers (ESPs), and the Machine Learning front in fighting spam. We conclude by measuring the impact of machine Learning-based filters and explore the promising offshoots of the latest developments. *

In [1]:
# import packages for showing mails are spam or not.
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn as sk

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
# Import/Loading data 
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('spam.csv')
df.head(7)

Saving spam.csv to spam.csv


Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...

In [3]:
# inspect data
df.groupby('Category').describe()


Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [4]:
# turning a spam/ham into numerical data ,creating a new coulmn called 'spam'
df ['spam'] = df['Category'].apply(lambda x:1 if x== 'spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [5]:
# create train/test split the data for 25%=x for testing and 75%=y for training.
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam ,test_size=0.25)
x_train.describe()

count                       4179
unique                      3916
top       Sorry, I'll call later
freq                          24
Name: Message, dtype: object

In [6]:
# Find the word count and store data as a matrix
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)
x_train_count

<4179x7471 sparse matrix of type '<class 'numpy.int64'>'
	with 55562 stored elements in Compressed Sparse Row format>

In [7]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
# Training The modelNB()
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [9]:
# pre test ham mail
email_ham = ["rewards money for click?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0])

In [10]:
# pre test spam mail
email_spam = ["good morning sir "]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([0])

In [11]:
# Testing the model 
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9820531227566404

**Thus we achieve a 0.9856% accuracy with Naive Bayes**